spring:
  application:
    name: conference-microservice
  datasource:
    url: jdbc:postgresql://localhost:5433/sbm?currentSchema=conf-svc
    username: postgres
    password: postgres
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      pool-name: "db-con-pool"
  jpa:
    properties:
      hibernate:
        default_schema: conf-svc
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    schemas: conf-svc
  freemarker:
    enabled: false

server:
  servlet:
    jsp:
      registered: false
  tomcat:
    max-connections: 20

# Debugging info
debug: false